# Netflix Content Analysis – Data Understanding & Cleaning

This notebook is the **first phase** of the Netflix Content Analysis project.  
In this phase, we will:
- Import the Netflix dataset
- Inspect its structure, data types, and missing values
- Perform basic cleaning to prepare it for feature engineering and exploratory data analysis

**Dataset Source:** DeepDataLake – Netflix Movies & TV Shows Metadata (~8,000 rows, CC0 licensed)

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("data.csv")  # Replace with your actual filename
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## 2. Basic Dataset Information

We will now:
- Check the shape of the dataset (rows × columns)
- View the column names
- Get a concise summary of data types and non-null counts

In [4]:

print(f"Dataset contains {df.shape[0]} rows and {df.shape[1]} columns.\n")

print("Column Names:", df.columns.tolist(), "\n")

df.info()

Dataset contains 8807 rows and 12 columns.

Column Names: ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

## 3. Missing Values Check

To ensure data quality, let's identify:
- Which columns have missing values
- The percentage of missing values per column

In [6]:

missing_counts = df.isnull().sum()
missing_percent = (missing_counts / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Values': missing_counts,
    'Percentage': missing_percent
}).sort_values(by='Percentage', ascending=False)

missing_df

              Missing Values  Percentage
director                2634   29.908028
country                  831    9.435676
cast                     825    9.367549
date_added                10    0.113546
rating                     4    0.045418
duration                   3    0.034064
show_id                    0    0.000000
type                       0    0.000000
title                      0    0.000000
release_year               0    0.000000
listed_in                  0    0.000000
description                0    0.000000

## 4. Initial Observations & Data Cleaning Plan

From the missing values check, we observe:
- `director` has ~30% missing values — expected, as some shows list no specific director
- `country` and `cast` have ~9% missing values — we can keep them as NaN for now, as they may still be useful later
- `date_added`, `rating`, `duration` have very few missing values — we can handle them individually
- `show_id`, `type`, `title`, `release_year`, `listed_in`, and `description` have no missing values

**Cleaning Plan:**
1. Convert `date_added` to datetime format
2. Standardize text columns by stripping spaces
3. Decide whether to fill or leave missing values based on column importance
4. Ensure `release_year` and other numeric fields are in the correct format

In [8]:
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'], format='mixed', errors='coerce')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

. Explore Key Categorical Columns

We will check:
- The unique values in `type`, `rating`, and `duration`
- This will help us understand possible inconsistencies before cleaning

In [9]:
print("Unique values in 'type':", df['type'].unique(), "\n")
print("Unique values in 'rating':", df['rating'].unique(), "\n")
print("Unique values in 'duration':", df['duration'].unique(), "\n")

Unique values in 'type': ['Movie' 'TV Show']

Unique values in 'rating': ['PG-13' 'TV-MA' 'PG' 'TV-14' 'TV-PG' 'TV-Y' 'TV-Y7' 'R' 'TV-G' 'G'
 'NC-17' '74 min' '84 min' '66 min' 'NR' nan 'TV-Y7-FV' 'UR']

Unique values in 'duration': ['90 min' '2 Seasons' '1 Season' '91 min' '125 min' '9 Seasons' '104 min'
 '127 min' '4 Seasons' '67 min' '94 min' '5 Seasons' '161 min' '61 min'
 '166 min' '147 min' '103 min' '97 min' '106 min' '111 min' '3 Seasons'
 '110 min' '105 min' '96 min' '124 min' '116 min' '98 min' '23 min'
 '115 min' '122 min' '99 min' '88 min' '100 min' '6 Seasons' '102 min'
 '93 min' '95 min' '85 min' '83 min' '113 min' '13 min' '182 min' '48 min'
 '145 min' '87 min' '92 min' '80 min' '117 min' '128 min' '119 min'
 '143 min' '114 min' '118 min' '108 min' '63 min' '121 min' '142 min'
 '154 min' '120 min' '82 min' '109 min' '101 min' '86 min' '229 min'
 '76 min' '89 min' '156 min' '112 min' '107 min' '129 min' '135 min'
 '136 min' '165 min' '150 min' '133 min' '70 min' '84 min' '140 min'
 '78 min' '7 Seasons' '64 min' '59 min' '139 min' '69 min' '148 min'
 '189 min' '141 min' '130 min' '138 min' '81 min' '132 min' '10 Seasons'
 '123 min' '65 min' '68 min' '66 min' '62 min' '74 min' '131 min' '39 min'
 '46 min' '38 min' '8 Seasons' '17 Seasons' '126 min' '155 min' '159 min'
 '137 min' '12 min' '273 min' '36 min' '34 min' '77 min' '60 min' '49 min'
 '58 min' '72 min' '204 min' '212 min' '25 min' '73 min' '29 min' '47 min'
 '32 min' '35 min' '71 min' '149 min' '33 min' '15 min' '54 min' '224 min'
 '162 min' '37 min' '75 min' '79 min' '55 min' '158 min' '164 min'
 '173 min' '181 min' '185 min' '21 min' '24 min' '51 min' '151 min'
 '42 min' '22 min' '134 min' '177 min' '13 Seasons' '52 min' '14 min'
 '53 min' '8 min' '57 min' '28 min' '50 min' '9 min' '26 min' '45 min'
 '171 min' '27 min' '44 min' '146 min' '20 min' '157 min' '17 min'
 '203 min' '41 min' '30 min' '194 min' '15 Seasons' '233 min' '237 min'
 '230 min' '195 min' '253 min' '152 min' '190 min' '160 min' '208 min'
 '180 min' '144 min' '5 min' '174 min' '170 min' '192 min' '209 min'
 '187 min' '172 min' '16 min' '186 min' '11 min' '193 min' '176 min'
 '56 min' '169 min' '40 min' '10 min' '3 min' '168 min' '312 min'
 '153 min' '214 min' '31 min' '163 min' '19 min' '12 Seasons' nan
 '179 min' '11 Seasons' '43 min' '200 min' '196 min' '167 min' '178 min'
 '228 min' '18 min' '205 min' '201 min' '191 min']


 Handling Missing Values

Our approach:
- `director`: Keep as NaN for now, as missing directors are common for shows and some content types
- `country` and `cast`: Keep as NaN for now; we may use them in specific analyses even if incomplete
- `date_added`, `rating`, `duration`: Fill missing values with suitable defaults

In [10]:
df['rating'] = df['rating'].fillna('Unknown')
df['duration'] = df['duration'].fillna('Unknown')
df['date_added'] = df['date_added'].fillna(pd.Timestamp("1900-01-01"))

## . Standardizing `rating` and `duration`

- `rating`: Standardize values by ensuring consistent formatting (e.g., removing extra spaces)
- `duration`: Split into numeric value and unit (Minutes or Seasons) for easier analysis

In [11]:
df['rating'] = df['rating'].str.strip()

df[['duration_value', 'duration_unit']] = df['duration'].str.extract(r'(\d+)\s*(\w+)')
df['duration_value'] = pd.to_numeric(df['duration_value'], errors='coerce')
df['duration_unit'] = df['duration_unit'].str.capitalize()

##  Final Clean Dataset Overview

We will:
- View the first few rows after cleaning
- Get updated dataset info
- Ensure there are no major data type issues before moving to feature engineering

In [12]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_value,duration_unit
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90.0,Min
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2.0,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1.0,Season
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1.0,Season
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2.0,Seasons

In [13]:
df.info

<bound method DataFrame.info of      show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

     date_added  release_year rating   duration  \
0    2021-09-25          2020  PG-13     90 min
1    2021-09-24          2021  TV-MA  2 Seasons
2    2021-09-24          2021  TV-MA   1 Season
3    2021-09-24          2021  TV-MA   1 Season
4    2021-09-24          2021  TV-MA  2 Seasons
...         ...           ...    ...        ...
8802 2019-11-20          2007      R    158 min
8803 2019-07-01          2018  TV-Y7  2 Seasons
8804 2019-11-01          2009      R     88 min
8805 2020-01-11          2006     PG     88 min
8806 2019-03-02          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description  duration_value  \
0     As her father nears the end of his life, filmm...            90.0
1     After crossing paths at a party, a Cape Town t...             2.0
2     To protect his family from a powerful drug lor...             1.0
3     Feuds, flirtations and toilet talk go down amo...             1.0
4     In a city of coaching centers known to train I...             2.0
...                                                 ...             ...
8802  A political cartoonist, a crime reporter and a...           158.0
8803  While living alone in a spooky town, a young g...             2.0
8804  Looking to survive in a world taken over by zo...            88.0
8805  Dragged from civilian life, a former superhero...            88.0
8806  A scrappy but poor boy worms his way into a ty...           111.0

     duration_unit
0              Min
1          Seasons
2           Season
3           Season
4          Seasons
...            ...
8802           Min
8803       Seasons
8804           Min
8805           Min
8806           Min

[8807 rows x 14 columns]>

In [14]:
df.isnull().sum()

show_id              0
type                 0
title                0
director          2634
cast               825
country            831
date_added           0
release_year         0
rating               0
duration             0
listed_in            0
description          0
duration_value       3
duration_unit        3
dtype: int64

In [16]:
df.to_csv('data_cleaned.csv')